# Run with: R --no-save <R-3.3.3-modules.R
CRANsite <- "http://cran.r-project.org"
#
# Packages installed through the UGent EasyBuild blocks as of
# the 2016b toolchain, minus the packages that need patches
# and the dependencies of those packages. They are still
# installed through EasyBuild.
#
# install.packages('Rmpi', repos=CRANsite, type="source", configure.args='--with-Rmpi-type=INTELMPI')
install.packages("BH",                  repos=CRANsite, type="source")
install.packages("Rcpp",                repos=CRANsite, type="source")
install.packages("bigmemory.sri",       repos=CRANsite, type="source")
Sys.setenv( PKG_CXXFLAGS='-wd308' )
install.packages('bigmemory',           repos=CRANsite, type="source")
install.packages('multicool',           repos=CRANsite, type="source")
Sys.unsetenv( 'PKG_CXXFLAGS')
install.packages('RcppArmadillo',       repos=CRANsite, type="source")
install.packages('lattice',             repos=CRANsite, type="source")
install.packages('zoo',                 repos=CRANsite, type="source")
install.packages('timeDate',            repos=CRANsite, type="source")
install.packages('quadprog',            repos=CRANsite, type="source")
install.packages('tseries',             repos=CRANsite, type="source")
install.packages('fracdiff',            repos=CRANsite, type="source")
install.packages('nnet',                repos=CRANsite, type="source")
install.packages('colorspace',          repos=CRANsite, type="source")
install.packages('digest',              repos=CRANsite, type="source")
install.packages('gtable',              repos=CRANsite, type="source")
install.packages('MASS',                repos=CRANsite, type="source")
install.packages('plyr',                repos=CRANsite, type="source")
install.packages('stringi',             repos=CRANsite, type="source")
install.packages('magrittr',            repos=CRANsite, type="source")
install.packages('stringr',             repos=CRANsite, type="source")
install.packages('reshape2',            repos=CRANsite, type="source")
install.packages('RColorBrewer',        repos=CRANsite, type="source")
install.packages('dichromat',           repos=CRANsite, type="source")
install.packages('munsell',             repos=CRANsite, type="source")
install.packages('labeling',            repos=CRANsite, type="source")
install.packages('scales',              repos=CRANsite, type="source")
install.packages('assertthat',          repos=CRANsite, type="source")
install.packages('lazyeval',            repos=CRANsite, type="source")
install.packages('tibble',              repos=CRANsite, type="source")
install.packages('ggplot2',             repos=CRANsite, type="source")
install.packages('lmtest',              repos=CRANsite, type="source")
Sys.setenv( PKG_CXXFLAGS='-wd308' )
install.packages('forecast',            repos=CRANsite, type="source")
Sys.unsetenv( 'PKG_CXXFLAGS')
install.packages("bit",                 repos=CRANsite, type="source")
install.packages("filehash",            repos=CRANsite, type="source")
install.packages("ff",                  repos=CRANsite, type="source")
install.packages("bnlearn",             repos=CRANsite, type="source")
install.packages("bootstrap",           repos=CRANsite, type="source")
install.packages("combinat",            repos=CRANsite, type="source")
install.packages("deal",                repos=CRANsite, type="source")
install.packages("fdrtool",             repos=CRANsite, type="source")
install.packages("formatR",             repos=CRANsite, type="source")
install.packages("gtools",              repos=CRANsite, type="source")
install.packages("gdata",               repos=CRANsite, type="source")
install.packages("GSA",                 repos=CRANsite, type="source")
install.packages("highr",               repos=CRANsite, type="source")
install.packages("infotheo",            repos=CRANsite, type="source")
install.packages("lars",                repos=CRANsite, type="source")
install.packages("lazy",                repos=CRANsite, type="source")
install.packages("kernlab",             repos=CRANsite, type="source")
install.packages("mime",                repos=CRANsite, type="source")
install.packages("markdown",            repos=CRANsite, type="source")
install.packages("mlbench",             repos=CRANsite, type="source")
install.packages("NLP",                 repos=CRANsite, type="source")
install.packages("mclust",              repos=CRANsite, type="source")
install.packages("RANN",                repos=CRANsite, type="source")
install.packages("rmeta",               repos=CRANsite, type="source")
install.packages("segmented",           repos=CRANsite, type="source")
install.packages("som",                 repos=CRANsite, type="source")
install.packages("SuppDists",           repos=CRANsite, type="source")
install.packages("stabledist",          repos=CRANsite, type="source")
install.packages("survivalROC",         repos=CRANsite, type="source")
install.packages("pspline",             repos=CRANsite, type="source")
install.packages("longmemo",            repos=CRANsite, type="source")
install.packages("ADGofTest",           repos=CRANsite, type="source")
install.packages("ade4",                repos=CRANsite, type="source")
install.packages("AlgDesign",           repos=CRANsite, type="source")
install.packages("base64enc",           repos=CRANsite, type="source")
install.packages("brew",                repos=CRANsite, type="source")
install.packages("Brobdingnag",         repos=CRANsite, type="source")
install.packages("corpcor",             repos=CRANsite, type="source")
install.packages("longitudinal",        repos=CRANsite, type="source")
install.packages("backports",           repos=CRANsite, type="source")
install.packages("checkmate",           repos=CRANsite, type="source")
install.packages("cubature",            repos=CRANsite, type="source")
install.packages("DEoptimR",            repos=CRANsite, type="source")
install.packages("fastmatch",           repos=CRANsite, type="source")
install.packages("ffbase",              repos=CRANsite, type="source")
install.packages("iterators",           repos=CRANsite, type="source")
install.packages("maps",                repos=CRANsite, type="source")
install.packages("nnls",                repos=CRANsite, type="source")
install.packages("sendmailR",           repos=CRANsite, type="source")
install.packages("spam",                repos=CRANsite, type="source")
install.packages("subplex",             repos=CRANsite, type="source")
install.packages("evaluate",            repos=CRANsite, type="source")
install.packages("logspline",           repos=CRANsite, type="source")
install.packages("ncbit",               repos=CRANsite, type="source")
install.packages("permute",             repos=CRANsite, type="source")
install.packages("plotrix",             repos=CRANsite, type="source")
install.packages("randomForest",        repos=CRANsite, type="source")
install.packages("scatterplot3d",       repos=CRANsite, type="source")
install.packages("SparseM",             repos=CRANsite, type="source")
install.packages("tripack",             repos=CRANsite, type="source")
install.packages("irace",               repos=CRANsite, type="source")
install.packages("rJava",               repos=CRANsite, type="source")
install.packages("latticeExtra",        repos=CRANsite, type="source")
install.packages("Matrix",              repos=CRANsite, type="source")
install.packages("png",                 repos=CRANsite, type="source")
install.packages("pROC",                repos=CRANsite, type="source")
install.packages("BB",                  repos=CRANsite, type="source")
install.packages("BBmisc",              repos=CRANsite, type="source")
install.packages("fail",                repos=CRANsite, type="source")
install.packages("rlecuyer",            repos=CRANsite, type="source")
install.packages("snow",                repos=CRANsite, type="source")
install.packages("tree",                repos=CRANsite, type="source")
install.packages("pls",                 repos=CRANsite, type="source")
install.packages("class",               repos=CRANsite, type="source")
install.packages("e1071",               repos=CRANsite, type="source")
install.packages("nlme",                repos=CRANsite, type="source")
install.packages("minqa",               repos=CRANsite, type="source")
install.packages("RcppEigen",           repos=CRANsite, type="source")
install.packages("MatrixModels",        repos=CRANsite, type="source")
install.packages("quantreg",            repos=CRANsite, type="source")
install.packages("mgcv",                repos=CRANsite, type="source")
install.packages("robustbase",          repos=CRANsite, type="source")
install.packages("sp",                  repos=CRANsite, type="source")
install.packages("vcd",                 repos=CRANsite, type="source")
install.packages("snowfall",            repos=CRANsite, type="source")
install.packages("rpart",               repos=CRANsite, type="source")
install.packages("survival",            repos=CRANsite, type="source")
install.packages("mice",                repos=CRANsite, type="source")
install.packages("urca",                repos=CRANsite, type="source")
install.packages("logistf",             repos=CRANsite, type="source")
install.packages("akima",               repos=CRANsite, type="source")
install.packages("bitops",              repos=CRANsite, type="source")
install.packages("boot",                repos=CRANsite, type="source")
install.packages("mixtools",            repos=CRANsite, type="source")
install.packages("cluster",             repos=CRANsite, type="source")
install.packages("gclus",               repos=CRANsite, type="source")
install.packages("coda",                repos=CRANsite, type="source")
install.packages("codetools",           repos=CRANsite, type="source")
install.packages("foreach",                     repos=CRANsite, type="source")
install.packages("doMC",                        repos=CRANsite, type="source")
install.packages("DBI",                         repos=CRANsite, type="source")
install.packages("foreign",                     repos=CRANsite, type="source")
install.packages("gam",                         repos=CRANsite, type="source")
install.packages("gamlss.data",         repos=CRANsite, type="source")
install.packages("gamlss.dist",         repos=CRANsite, type="source")
install.packages("hwriter",                     repos=CRANsite, type="source")
install.packages("KernSmooth",          repos=CRANsite, type="source")
install.packages("xts",                         repos=CRANsite, type="source")
install.packages("TTR",                         repos=CRANsite, type="source")
install.packages("quantmod",            repos=CRANsite, type="source")
install.packages("mnormt",                      repos=CRANsite, type="source")
install.packages("mvtnorm",                     repos=CRANsite, type="source")
install.packages("pcaPP",                       repos=CRANsite, type="source")
install.packages("numDeriv",            repos=CRANsite, type="source")
install.packages("lava",                        repos=CRANsite, type="source")
install.packages("prodlim",                     repos=CRANsite, type="source")
install.packages("pscl",                        repos=CRANsite, type="source")
install.packages("RSQLite",                     repos=CRANsite, type="source")
install.packages("BatchJobs",           repos=CRANsite, type="source")
install.packages("sandwich",            repos=CRANsite, type="source")
install.packages("sfsmisc",                     repos=CRANsite, type="source")
install.packages("spatial",                     repos=CRANsite, type="source")
install.packages("VGAM",                        repos=CRANsite, type="source")
install.packages("waveslim",            repos=CRANsite, type="source")
install.packages("xtable",                      repos=CRANsite, type="source")
install.packages("profileModel",        repos=CRANsite, type="source")
install.packages("brglm",                       repos=CRANsite, type="source")
install.packages("deSolve",                     repos=CRANsite, type="source")
install.packages("tseriesChaos",        repos=CRANsite, type="source")
install.packages("fastICA",                     repos=CRANsite, type="source")
install.packages("R.methodsS3",         repos=CRANsite, type="source")
install.packages("R.oo",                        repos=CRANsite, type="source")
install.packages("cgdsr",                       repos=CRANsite, type="source")
install.packages("R.utils",                     repos=CRANsite, type="source")
install.packages("R.matlab",            repos=CRANsite, type="source")
install.packages("gbm",                         repos=CRANsite, type="source")
install.packages("Formula",                     repos=CRANsite, type="source")
install.packages("acepack",                     repos=CRANsite, type="source")
install.packages("proto",                       repos=CRANsite, type="source")
install.packages("gridExtra",           repos=CRANsite, type="source")
install.packages("chron",                       repos=CRANsite, type="source")
install.packages("data.table",          repos=CRANsite, type="source")
install.packages("Hmisc",                       repos=CRANsite, type="source")
install.packages("fastcluster",         repos=CRANsite, type="source")
install.packages("registry",            repos=CRANsite, type="source")
install.packages("pkgmaker",            repos=CRANsite, type="source")
install.packages("rngtools",            repos=CRANsite, type="source")
install.packages("doParallel",          repos=CRANsite, type="source")
install.packages("gridBase",            repos=CRANsite, type="source")
install.packages("NMF",                         repos=CRANsite, type="source")
install.packages("irlba",                       repos=CRANsite, type="source")
install.packages("igraph",                      repos=CRANsite, type="source")
install.packages("GeneNet",                     repos=CRANsite, type="source")
install.packages("ape",                         repos=CRANsite, type="source")
install.packages("htmltools",           repos=CRANsite, type="source")
install.packages("RJSONIO",                     repos=CRANsite, type="source")
install.packages("caTools",                     repos=CRANsite, type="source")
install.packages("gplots",                      repos=CRANsite, type="source")
install.packages("ROCR",                        repos=CRANsite, type="source")
install.packages('httpuv',                      repos=CRANsite, type="source")
install.packages("R6",                          repos=CRANsite, type="source")
install.packages("jsonlite",            repos=CRANsite, type="source")
install.packages("rjson",                       repos=CRANsite, type="source")
install.packages("shiny",                       repos=CRANsite, type="source")
install.packages("seqinr",                      repos=CRANsite, type="source")
install.packages("LearnBayes",          repos=CRANsite, type="source")
install.packages("deldir",                      repos=CRANsite, type="source")
install.packages("gmodels",                     repos=CRANsite, type="source")
install.packages("spdep",                       repos=CRANsite, type="source")
install.packages("tibble",                      repos=CRANsite, type="source")
install.packages("dplyr",                       repos=CRANsite, type="source")
install.packages("vegan",                       repos=CRANsite, type="source")
install.packages("adegenet",            repos=CRANsite, type="source")
install.packages("rncl",                        repos=CRANsite, type="source")
install.packages("XML",                         repos=CRANsite, type="source")
install.packages("memoise",                     repos=CRANsite, type="source")
install.packages("crayon",                      repos=CRANsite, type="source")
install.packages("praise",                      repos=CRANsite, type="source")
install.packages("testthat",            repos=CRANsite, type="source")
install.packages("yaml",                        repos=CRANsite, type="source")
install.packages("knitr",                       repos=CRANsite, type="source")
install.packages("rmarkdown",           repos=CRANsite, type="source")
install.packages("curl",                        repos=CRANsite, type="source")
install.packages("openssl",                     repos=CRANsite, type="source")
install.packages("httr",                        repos=CRANsite, type="source")
install.packages("reshape",                     repos=CRANsite, type="source")
install.packages("xml2",                        repos=CRANsite, type="source")
install.packages("bold",                        repos=CRANsite, type="source")
install.packages("rredlist",            repos=CRANsite, type="source")
install.packages("rentrez",                     repos=CRANsite, type="source")
install.packages("rotl",                        repos=CRANsite, type="source")
install.packages("taxize",                      repos=CRANsite, type="source")
install.packages("tidyr",                       repos=CRANsite, type="source")
install.packages("uuid",                        repos=CRANsite, type="source")
install.packages("RNeXML",                      repos=CRANsite, type="source")
install.packages("phylobase",           repos=CRANsite, type="source")
install.packages("adephylo",            repos=CRANsite, type="source")
install.packages("animation",           repos=CRANsite, type="source")
install.packages("calibrate",           repos=CRANsite, type="source")
install.packages("clusterGeneration",   repos=CRANsite, type="source")
install.packages("raster",                      repos=CRANsite, type="source")
install.packages("dismo",                       repos=CRANsite, type="source")
install.packages("expm",                        repos=CRANsite, type="source")
install.packages("extrafontdb",         repos=CRANsite, type="source")
install.packages("Rttf2pt1",            repos=CRANsite, type="source")
install.packages("extrafont",           repos=CRANsite, type="source")
install.packages("fields",                      repos=CRANsite, type="source")
install.packages("shapefiles",          repos=CRANsite, type="source")
install.packages("fossil",                      repos=CRANsite, type="source")
install.packages("geiger",                      repos=CRANsite, type="source")
install.packages("glmnet",                      repos=CRANsite, type="source")
install.packages("rgl",                         repos=CRANsite, type="source")
install.packages("labdsv",                      repos=CRANsite, type="source")
install.packages("stabs",                       repos=CRANsite, type="source")
install.packages("modeltools",          repos=CRANsite, type="source")
install.packages("strucchange",         repos=CRANsite, type="source")
install.packages("TH.data",                     repos=CRANsite, type="source")
install.packages("multcomp",            repos=CRANsite, type="source")
install.packages("coin",                        repos=CRANsite, type="source")
install.packages("party",                       repos=CRANsite, type="source")
install.packages("mboost",                      repos=CRANsite, type="source")
install.packages("msm",                         repos=CRANsite, type="source")
install.packages("nor1mix",                     repos=CRANsite, type="source")
install.packages("np",                          repos=CRANsite, type="source")
install.packages("polynom",                     repos=CRANsite, type="source")
install.packages("polspline",           repos=CRANsite, type="source")
install.packages("rms",                         repos=CRANsite, type="source")
install.packages("RWekajars",           repos=CRANsite, type="source")
install.packages("RWeka",                       repos=CRANsite, type="source")
install.packages("slam",                        repos=CRANsite, type="source")
install.packages("tm",                          repos=CRANsite, type="source")
install.packages("TraMineR",            repos=CRANsite, type="source")
install.packages("chemometrics",        repos=CRANsite, type="source")
install.packages("FNN",                         repos=CRANsite, type="source")
install.packages("ipred",                       repos=CRANsite, type="source")
install.packages("statmod",                     repos=CRANsite, type="source")
install.packages("miscTools",           repos=CRANsite, type="source")
install.packages("maxLik",                      repos=CRANsite, type="source")
install.packages("mlogit",                      repos=CRANsite, type="source")
install.packages("getopt",                      repos=CRANsite, type="source")
install.packages("gsalib",                      repos=CRANsite, type="source")
install.packages("optparse",            repos=CRANsite, type="source")
install.packages("klaR",                        repos=CRANsite, type="source")
install.packages("neuRosim",            repos=CRANsite, type="source")
install.packages("locfit",                      repos=CRANsite, type="source")
install.packages("GGally",                      repos=CRANsite, type="source")
install.packages("beanplot",            repos=CRANsite, type="source")
install.packages("clValid",                     repos=CRANsite, type="source")
install.packages("matrixStats",         repos=CRANsite, type="source")
install.packages("DiscriMiner",         repos=CRANsite, type="source")
install.packages("ellipse",                     repos=CRANsite, type="source")
install.packages("leaps",                       repos=CRANsite, type="source")
install.packages("nloptr",                      repos=CRANsite, type="source")
install.packages("lme4",                        repos=CRANsite, type="source")
install.packages("pbkrtest",            repos=CRANsite, type="source")
install.packages("car",                         repos=CRANsite, type="source")
install.packages("flashClust",          repos=CRANsite, type="source")
install.packages("FactoMineR",          repos=CRANsite, type="source")
install.packages("flexclust",           repos=CRANsite, type="source")
install.packages("flexmix",                     repos=CRANsite, type="source")
install.packages("prabclus",            repos=CRANsite, type="source")
install.packages("diptest",                     repos=CRANsite, type="source")
install.packages("trimcluster",         repos=CRANsite, type="source")
install.packages("fpc",                         repos=CRANsite, type="source")
install.packages("BiasedUrn",           repos=CRANsite, type="source")
install.packages("TeachingDemos",       repos=CRANsite, type="source")
install.packages("kohonen",                     repos=CRANsite, type="source")
install.packages("base64",                      repos=CRANsite, type="source")
install.packages("doRNG",                       repos=CRANsite, type="source")
install.packages("nleqslv",                     repos=CRANsite, type="source")
install.packages("RGCCA",                       repos=CRANsite, type="source")
install.packages("pheatmap",            repos=CRANsite, type="source")
install.packages("openxlsx",            repos=CRANsite, type="source")
install.packages("pvclust",                     repos=CRANsite, type="source")
install.packages("RCircos",                     repos=CRANsite, type="source")
install.packages("lambda.r",            repos=CRANsite, type="source")
install.packages("futile.options",      repos=CRANsite, type="source")
install.packages("futile.logger",       repos=CRANsite, type="source")
install.packages("VennDiagram",         repos=CRANsite, type="source")
install.packages("xlsxjars",            repos=CRANsite, type="source")
install.packages("xlsx",                        repos=CRANsite, type="source")
install.packages("fma",                         repos=CRANsite, type="source")
install.packages("expsmooth",           repos=CRANsite, type="source")
install.packages("fpp",                         repos=CRANsite, type="source")
install.packages("maptools",            repos=CRANsite, type="source")
install.packages("tensor",                      repos=CRANsite, type="source")
install.packages("polyclip",            repos=CRANsite, type="source")
install.packages("goftest",                     repos=CRANsite, type="source")
install.packages("spatstat",            repos=CRANsite, type="source")
install.packages("rgdal",                       repos=CRANsite, type="source")
install.packages("gdalUtils",           repos=CRANsite, type="source")
install.packages("pracma",                      repos=CRANsite, type="source")
install.packages("RCurl",                       repos=CRANsite, type="source")
install.packages("bio3d",                       repos=CRANsite, type="source")
install.packages("AUC",                         repos=CRANsite, type="source")
install.packages("interpretR",          repos=CRANsite, type="source")
install.packages("cvAUC",                       repos=CRANsite, type="source")
install.packages("SuperLearner",        repos=CRANsite, type="source")
install.packages("lpSolve",                     repos=CRANsite, type="source")
install.packages("mediation",           repos=CRANsite, type="source")
install.packages("caret",                       repos=CRANsite, type="source")
install.packages("adabag",                      repos=CRANsite, type="source")
install.packages("parallelMap",         repos=CRANsite, type="source")
install.packages("ParamHelpers",        repos=CRANsite, type="source")
install.packages("ggvis",                       repos=CRANsite, type="source")
install.packages("mlr",                         repos=CRANsite, type="source")
install.packages("unbalanced",          repos=CRANsite, type="source")
install.packages("RSNNS",                       repos=CRANsite, type="source")
install.packages("abc.data",            repos=CRANsite, type="source")
install.packages("abc",                         repos=CRANsite, type="source")
install.packages("lhs",                         repos=CRANsite, type="source")
install.packages("tensorA",                     repos=CRANsite, type="source")
install.packages("EasyABC",                     repos=CRANsite, type="source")
install.packages("shape",                       repos=CRANsite, type="source")
install.packages("whisker",                     repos=CRANsite, type="source")
install.packages("rstudioapi",          repos=CRANsite, type="source")
install.packages("roxygen2",            repos=CRANsite, type="source")
install.packages("git2r",                       repos=CRANsite, type="source")
install.packages("rversions",           repos=CRANsite, type="source")
install.packages("withr",                       repos=CRANsite, type="source")
install.packages("devtools",            repos=CRANsite, type="source")
install.packages("Rook",                        repos=CRANsite, type="source")
install.packages("Cairo",                       repos=CRANsite, type="source")
install.packages("RMTstat",                     repos=CRANsite, type="source")
install.packages("Lmoments",            repos=CRANsite, type="source")
install.packages("distillery",          repos=CRANsite, type="source")
install.packages("extRemes",            repos=CRANsite, type="source")
install.packages("pixmap",                      repos=CRANsite, type="source")
install.packages("tkrplot",                     repos=CRANsite, type="source")
install.packages("misc3d",                      repos=CRANsite, type="source")
install.packages("ks",                          repos=CRANsite, type="source")
install.packages("logcondens",          repos=CRANsite, type="source")
install.packages("Iso",                         repos=CRANsite, type="source")
install.packages("penalized",           repos=CRANsite, type="source")
install.packages("clusterRepro",        repos=CRANsite, type="source")
install.packages("randomForestSRC",     repos=CRANsite, type="source")
install.packages("sm",                          repos=CRANsite, type="source")
install.packages("psych",                       repos=CRANsite, type="source")
install.packages("pbivnorm",            repos=CRANsite, type="source")
install.packages("lavaan",                      repos=CRANsite, type="source")
install.packages("matrixcalc",          repos=CRANsite, type="source")
install.packages("arm",                         repos=CRANsite, type="source")
install.packages("mi",                          repos=CRANsite, type="source")
install.packages("htmlwidgets",         repos=CRANsite, type="source")
install.packages("visNetwork",          repos=CRANsite, type="source")
install.packages("DiagrammeR",          repos=CRANsite, type="source")
install.packages("sem",                         repos=CRANsite, type="source")
install.packages("jpeg",                        repos=CRANsite, type="source")
install.packages("sna",                         repos=CRANsite, type="source")
install.packages("huge",                        repos=CRANsite, type="source")
install.packages("d3Network",           repos=CRANsite, type="source")
install.packages("ggm",                         repos=CRANsite, type="source")
install.packages("qgraph",                      repos=CRANsite, type="source")
install.packages("diveRsity",           repos=CRANsite, type="source")
install.packages("doSNOW",                      repos=CRANsite, type="source")
install.packages("phangorn",            repos=CRANsite, type="source")
install.packages("geepack",                     repos=CRANsite, type="source")
install.packages("lubridate",           repos=CRANsite, type="source")
install.packages("biom",                        repos=CRANsite, type="source")
install.packages("pim",                         repos=CRANsite, type="source")
#
# UAntwerpen-requested packages
# We rely on R to install all depencies that we may have missed.
#
# Dependencies
#
install.packages("truncnorm",           repos=CRANsite, type="source")
# Packages actually requested.
install.packages("gmnl",                        repos=CRANsite, type="source")
#
# BioConductor.
# We only install a subset of BioConductor packages.
#
source("https://bioconductor.org/biocLite.R")
biocLite(pkgs=c('BiocGenerics'),        suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('Biobase'),                     suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('DynDoc'),                      suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('edgeR'),                       suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('gdsfmt'),                      suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('illuminaio'),          suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('preprocessCore'),      suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('RNASeqPower'),         suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('Rsubread'),            suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('qvalue'),                      suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('widgetTools'),         suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('zlibbioc'),            suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('impute'),                      suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
install.packages("samr",                        repos=CRANsite, type="source")
biocLite(pkgs=c('tkWidgets'),           suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('Mfuzz'),                       suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('pcaMethods'),          suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('S4Vectors'),           suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('IRanges'),                     suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('GenomeInfoDb'),        suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('AnnotationDbi'),       suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('AnnotationForge'),     suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('GO.db'),                       suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('org.Hs.eg.db'),        suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('KEGG.db'),                     suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('PFAM.db'),                     suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('hgu133plus2.db'),      suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('TxDb.Hsapiens.UCSC.hg19.knownGene'),   suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('biomaRt'),                     suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('GenomeGraphs'),        suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('XVector'),                     suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('Biostrings'),          suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('GenomicRanges'),       suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('BiocParallel'),        suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('Rsamtools'),           suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('SummarizedExperiment'),        suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('GenomicAlignments'),   suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('ShortRead'),           suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('graph'),                       suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('Rgraphviz'),           suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('affyio'),                      suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('affy'),                        suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('limma'),                       suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('marray'),                      suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('CGHbase'),                     suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('RBGL'),                        suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('annaffy'),                     suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('gcrma'),                       suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('oligoClasses'),        suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('baySeq'),                      suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('DEGseq'),                      suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('rtracklayer'),         suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('GenomicFeatures'),     suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('bumphunter'),          suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('multtest'),            suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('siggenes'),            suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('genoset'),                     suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('NOISeq'),                      suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('annotate'),            suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('GSEABase'),            suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('genefilter'),          suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('Category'),            suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('GOstats'),                     suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('BSgenome'),            suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('VariantAnnotation'),   suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('interactiveDisplayBase'),      suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('AnnotationHub'),       suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('ensembldb'),           suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('biovizBase'),          suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('OrganismDbi'),         suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('ggbio'),                       suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('geneplotter'),         suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('DESeq2'),                      suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('ReportingTools'),      suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('affycoretools'),       suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('Homo.sapiens'),        suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('BSgenome.Hsapiens.UCSC.hg19'),         suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('AgiMicroRna'),         suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('geneLenDataBase'),     suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('goseq'),                       suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('KEGGREST'),            suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('KEGGgraph'),           suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('KEGGprofile'),         suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('GEOquery'),            suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('minfi'),                       suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('FDb.InfiniumMethylation.hg19'),        suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('methylumi'),           suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('lumi'),                        suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('maSigPro'),            suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('SPIA'),                        suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('Gviz'),                        suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('cummeRbund'),          suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('GenomicFiles'),        suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('derfinderHelper'),     suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('derfinder'),           suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('polyester'),           suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('sigaR'),                       suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('HCsnip'),                      suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('metagenomeSeq'),       suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
#
# Other requeste packages
#
# Mzmatch (Bart Cuypers), depends on BioConductor
install.packages("ptw",                         repos=CRANsite)
install.packages("tcltk2",                      repos=CRANsite)
source("https://bioconductor.org/biocLite.R")
biocLite(pkgs=c('ProtGenerics'),        suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('mzR'),                         suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
biocLite(pkgs=c('xcms'),                        suppressUpdates=TRUE, suppressAutoUpdate=FALSE, ask=FALSE)
install.packages("mzmatch.R",           repos="http://R-Forge.R-project.org")
