# Run with: R --no-save <R-4.0.2-modules.R
CRANsite <- "http://cran.r-project.org"

install.packages("BiocManager",         repos=CRANsite, type="source")
BiocManager::install(version = "3.11", update = FALSE)

#
# Packages installed through the UGent EasyBuild blocks as of
# the 2016b toolchain, minus the packages that need patches
# and the dependencies of those packages. They are still
# installed through EasyBuild.
#
install.packages("Rcpp",                repos=CRANsite, type="source")

install.packages('Rmpi', repos=CRANsite, type="source", configure.args='--with-Rmpi-type=INTELMPI --with-Rmpi-libpath=$I_MPI_ROOT/intel64/lib/release --with-Rmpi-include=$I_MPI_ROOT/intel64/include')

install.packages("XML",                 repos=CRANsite, type="source")

# ModelMetrics supports OpenMP
install.packages("data.table",          repos=CRANsite, type="source")
Sys.setenv( PKG_CXXFLAGS='-qopenmp' )
install.packages("ModelMetrics",        repos=CRANsite, type="source")
Sys.unsetenv( 'PKG_CXXFLAGS')

# tseries and dependencies
install.packages('curl',                repos=CRANsite, type="source")
install.packages("lattice",             repos=CRANsite, type="source")
install.packages('zoo',                 repos=CRANsite, type="source")
install.packages('xts',                 repos=CRANsite, type="source")
install.packages('TTR',                 repos=CRANsite, type="source")
install.packages('quadprog',            repos=CRANsite, type="source")
install.packages('quantmod',            repos=CRANsite, type="source")
# tseries 1.10-47 fails to install due to the use of a non-standard filename extension.
#install.packages('tseries',             repos=CRANsite, type="source")
packageurl <- "https://cran.r-project.org/src/contrib/Archive/tseries/tseries_0.10-46.tar.gz"
install.packages(packageurl,            repos=NULL,     type="source")

# sf which had trouble with the GDAL library in 2019b
install.packages("units",               repos=CRANsite, type="source")
install.packages('magrittr',            repos=CRANsite, type="source")
install.packages("MASS",                repos=CRANsite, type="source")
install.packages("class",               repos=CRANsite, type="source")
install.packages("e1071",               repos=CRANsite, type="source")
install.packages("KernSmooth",          repos=CRANsite, type="source")
install.packages("classInt",            repos=CRANsite, type="source")
# sf does not install due to problems with GDAL
install.packages("sf",                  repos=CRANsite, type="source")

# penalized: Use data alignment or not?
install.packages('Matrix',              repos=CRANsite, type="source")
install.packages("survival",            repos=CRANsite, type="source")
install.packages('RcppArmadillo',       repos=CRANsite, type="source")
install.packages("penalized",           repos=CRANsite, type="source")

# Compilation of kohonen failed in 2019b.
install.packages("kohonen",             repos=CRANsite, type="source") # Compilation fails.

#Sys.setenv( PKG_CXXFLAGS='-diag-dsable 308' )
install.packages("Rtsne",               repos=CRANsite, type="source")
#Sys.unsetenv( 'PKG_CXXFLAGS')

#Sys.setenv( PKG_CXXFLAGS='-diag-disable 308 -diag-disable 858' )
Sys.setenv( PKG_CXXFLAGS='-diag-disable 858' )
install.packages('multicool',           repos=CRANsite, type="source")
Sys.unsetenv( 'PKG_CXXFLAGS')
install.packages("BH",                  repos=CRANsite, type="source")

install.packages('bigmemory.sri',       repos=CRANsite, type="source")
#Sys.setenv( PKG_CXXFLAGS='-diag-disable 308 -diag-disable 858' )
Sys.setenv( PKG_CXXFLAGS='-diag-disable 858' )
install.packages('bigmemory',           repos=CRANsite, type="source")
Sys.unsetenv( 'PKG_CXXFLAGS')

install.packages("jpeg",                repos=CRANsite, type="source")
install.packages("png",                 repos=CRANsite, type="source")
install.packages("Cairo",               repos=CRANsite, type="source")
install.packages("sys",                 repos=CRANsite, type="source")
install.packages("askpass",             repos=CRANsite, type="source")
install.packages("openssl",             repos=CRANsite, type="source")
install.packages("bitops",              repos=CRANsite, type="source")
install.packages("RCurl",               repos=CRANsite, type="source")
install.packages("sp",                  repos=CRANsite, type="source")
install.packages("rgeos",               repos=CRANsite, type="source")


install.packages('backports',           repos=CRANsite, type="source")
install.packages("bit",                 repos=CRANsite, type="source")
install.packages("bit64",               repos=CRANsite, type="source")
install.packages('assertthat',          repos=CRANsite, type="source")
install.packages("prettyunits",         repos=CRANsite, type="source")
install.packages('digest',              repos=CRANsite, type="source")
install.packages("yaml",                repos=CRANsite, type="source")
install.packages('plyr',                repos=CRANsite, type="source")
install.packages("mime",                repos=CRANsite, type="source")
install.packages('R6',                  repos=CRANsite, type="source")
install.packages("jsonlite",            repos=CRANsite, type="source")
install.packages("httr",                repos=CRANsite, type="source")
install.packages('rlang',               repos=CRANsite, type="source")
install.packages('ellipsis',            repos=CRANsite, type="source")
install.packages('glue',                repos=CRANsite, type="source")
install.packages('zeallot',             repos=CRANsite, type="source")
install.packages('vctrs',               repos=CRANsite, type="source")
install.packages("blob",                repos=CRANsite, type="source")
install.packages("plogr",               repos=CRANsite, type="source")
install.packages("DBI",                 repos=CRANsite, type="source")
install.packages("memoise",             repos=CRANsite, type="source")
install.packages('pkgconfig',           repos=CRANsite, type="source")
install.packages("RSQLite",             repos=CRANsite, type="source")

install.packages("rgdal",               repos=CRANsite, type="source")

#
# From here on install through this script.
#

install.packages("abind",               repos=CRANsite, type="source")
install.packages("glasso",              repos=CRANsite, type="source")
install.packages("magic",               repos=CRANsite, type="source")
install.packages("lpSolve",             repos=CRANsite, type="source")
install.packages("linprog",             repos=CRANsite, type="source")
install.packages("RcppProgress",        repos=CRANsite, type="source")
install.packages("geometry",            repos=CRANsite, type="source")
install.packages('timeDate',            repos=CRANsite, type="source")
install.packages('fracdiff',            repos=CRANsite, type="source")
install.packages('nnet',                repos=CRANsite, type="source")
install.packages('colorspace',          repos=CRANsite, type="source")
install.packages('gtable',              repos=CRANsite, type="source")
install.packages('stringi',             repos=CRANsite, type="source")
install.packages('stringr',             repos=CRANsite, type="source")
install.packages('reshape2',            repos=CRANsite, type="source")
install.packages('RColorBrewer',        repos=CRANsite, type="source")
install.packages('dichromat',           repos=CRANsite, type="source")
install.packages('munsell',             repos=CRANsite, type="source")
install.packages('labeling',            repos=CRANsite, type="source")
install.packages('viridisLite',         repos=CRANsite, type="source")
install.packages('lifecycle',           repos=CRANsite, type="source")
install.packages('farver',              repos=CRANsite, type="source")
install.packages('scales',              repos=CRANsite, type="source")
install.packages('lazyeval',            repos=CRANsite, type="source")
install.packages('utf8',                repos=CRANsite, type="source")
install.packages('crayon',              repos=CRANsite, type="source")
install.packages('fansi',               repos=CRANsite, type="source")
install.packages('cli',                 repos=CRANsite, type="source")
install.packages('pillar',              repos=CRANsite, type="source")
install.packages('tibble',              repos=CRANsite, type="source")
install.packages('nlme',                repos=CRANsite, type="source")
install.packages('mgcv',                repos=CRANsite, type="source")
install.packages('withr',               repos=CRANsite, type="source")

# Dependencies pulled in via testthat
install.packages("evaluate",            repos=CRANsite, type="source")
install.packages("ps",                  repos=CRANsite, type="source")
install.packages("processx",            repos=CRANsite, type="source")
install.packages("callr",               repos=CRANsite, type="source")
install.packages("rprojroot",           repos=CRANsite, type="source")
install.packages("desc",                repos=CRANsite, type="source")
install.packages("pkgbuild",            repos=CRANsite, type="source")
install.packages("rstudioapi",          repos=CRANsite, type="source")
install.packages("pkgload",             repos=CRANsite, type="source")
install.packages("praise",              repos=CRANsite, type="source")
install.packages("testthat",            repos=CRANsite, type="source")
install.packages('isoband',             repos=CRANsite, type="source")
install.packages('ggplot2',             repos=CRANsite, type="source")
install.packages('lmtest',              repos=CRANsite, type="source")
install.packages('urca',                repos=CRANsite, type="source")
#Sys.setenv( PKG_CXXFLAGS='-diag-disable 308' )
install.packages('forecast',            repos=CRANsite, type="source") # Requires tseries; hard to move forward due to a complicated dependency tree
#Sys.unsetenv( 'PKG_CXXFLAGS')

install.packages("filehash",            repos=CRANsite, type="source")
install.packages("ff",                  repos=CRANsite, type="source")
install.packages("bnlearn",             repos=CRANsite, type="source")
install.packages("bootstrap",           repos=CRANsite, type="source")
install.packages("combinat",            repos=CRANsite, type="source")
install.packages("deal",                repos=CRANsite, type="source")
install.packages("fdrtool",             repos=CRANsite, type="source")
install.packages("formatR",             repos=CRANsite, type="source")
install.packages("gtools",              repos=CRANsite, type="source")
install.packages("gdata",               repos=CRANsite, type="source")
install.packages("GSA",                 repos=CRANsite, type="source")
install.packages("highr",               repos=CRANsite, type="source")
install.packages("infotheo",            repos=CRANsite, type="source")
install.packages("kernlab",             repos=CRANsite, type="source")
install.packages("lars",                repos=CRANsite, type="source")
install.packages("lazy",                repos=CRANsite, type="source")
install.packages("xfun",                repos=CRANsite, type="source")
install.packages("markdown",            repos=CRANsite, type="source")
install.packages("mlbench",             repos=CRANsite, type="source")
install.packages("NLP",                 repos=CRANsite, type="source")
install.packages("mclust",              repos=CRANsite, type="source")
install.packages("RANN",                repos=CRANsite, type="source")
install.packages("rmeta",               repos=CRANsite, type="source")
install.packages("segmented",           repos=CRANsite, type="source")
install.packages("som",                 repos=CRANsite, type="source")
install.packages("SuppDists",           repos=CRANsite, type="source")
install.packages("stabledist",          repos=CRANsite, type="source")
install.packages("survivalROC",         repos=CRANsite, type="source")
install.packages("pspline",             repos=CRANsite, type="source")
install.packages("longmemo",            repos=CRANsite, type="source")
install.packages("ADGofTest",           repos=CRANsite, type="source")
install.packages("pixmap",              repos=CRANsite, type="source")
install.packages("ade4",                repos=CRANsite, type="source")
install.packages("AlgDesign",           repos=CRANsite, type="source")
install.packages("base64enc",           repos=CRANsite, type="source")
install.packages("brew",                repos=CRANsite, type="source")
install.packages("Brobdingnag",         repos=CRANsite, type="source")
install.packages("corpcor",             repos=CRANsite, type="source")
install.packages("longitudinal",        repos=CRANsite, type="source")
install.packages("checkmate",           repos=CRANsite, type="source")
install.packages("cubature",            repos=CRANsite, type="source")
install.packages("DEoptimR",            repos=CRANsite, type="source")
install.packages("fastmatch",           repos=CRANsite, type="source")
install.packages("ffbase",              repos=CRANsite, type="source")
install.packages("iterators",           repos=CRANsite, type="source")
install.packages("maps",                repos=CRANsite, type="source")
install.packages("nnls",                repos=CRANsite, type="source")
install.packages("sendmailR",           repos=CRANsite, type="source")
install.packages("dotCall64",           repos=CRANsite, type="source")
install.packages("spam",                repos=CRANsite, type="source")
install.packages("subplex",             repos=CRANsite, type="source")
install.packages("logspline",           repos=CRANsite, type="source")
install.packages("ncbit",               repos=CRANsite, type="source")
install.packages("permute",             repos=CRANsite, type="source")
install.packages("plotrix",             repos=CRANsite, type="source")
install.packages("randomForest",        repos=CRANsite, type="source")
install.packages("scatterplot3d",       repos=CRANsite, type="source")
install.packages("SparseM",             repos=CRANsite, type="source")
install.packages("tripack",             repos=CRANsite, type="source")
install.packages("irace",               repos=CRANsite, type="source")
install.packages("rJava",               repos=CRANsite, type="source")
install.packages("latticeExtra",        repos=CRANsite, type="source")
install.packages("pROC",                repos=CRANsite, type="source")
install.packages("BB",                  repos=CRANsite, type="source")
install.packages("BBmisc",              repos=CRANsite, type="source")
install.packages("fail",                repos=CRANsite, type="source")
install.packages("rlecuyer",            repos=CRANsite, type="source")
install.packages("snow",                repos=CRANsite, type="source")
install.packages("tree",                repos=CRANsite, type="source")
install.packages("pls",                 repos=CRANsite, type="source")
install.packages("minqa",               repos=CRANsite, type="source")
install.packages("RcppEigen",           repos=CRANsite, type="source")
install.packages("MatrixModels",        repos=CRANsite, type="source")
install.packages("quantreg",            repos=CRANsite, type="source")
install.packages("robustbase",          repos=CRANsite, type="source")
install.packages("vcd",                 repos=CRANsite, type="source")
install.packages("snowfall",            repos=CRANsite, type="source")
install.packages("rpart",               repos=CRANsite, type="source")
install.packages("boot",                repos=CRANsite, type="source")
install.packages("nloptr",              repos=CRANsite, type="source")
install.packages("ucminf",              repos=CRANsite, type="source")
install.packages("numDeriv",            repos=CRANsite, type="source")
install.packages("clipr",               repos=CRANsite, type="source")
install.packages("statmod",             repos=CRANsite, type="source")
install.packages("lme4",                repos=CRANsite, type="source")
install.packages("ordinal",             repos=CRANsite, type="source")
install.packages("forcats",             repos=CRANsite, type="source")
install.packages("hms",                 repos=CRANsite, type="source")
install.packages("readr",               repos=CRANsite, type="source")
install.packages("generics",            repos=CRANsite, type="source")
install.packages("purrr",               repos=CRANsite, type="source")
install.packages("tidyselect",          repos=CRANsite, type="source")
install.packages("dplyr",                repos=CRANsite, type="source")
install.packages("tidyr",               repos=CRANsite, type="source")
install.packages("pan",                 repos=CRANsite, type="source")
install.packages("jomo",                repos=CRANsite, type="source")
install.packages("haven",               repos=CRANsite, type="source")
install.packages("broom",               repos=CRANsite, type="source")
install.packages("mitml",               repos=CRANsite, type="source")
install.packages("mice",                repos=CRANsite, type="source")
install.packages("logistf",             repos=CRANsite, type="source")
install.packages("akima",               repos=CRANsite, type="source")
install.packages("mixtools",            repos=CRANsite, type="source")
install.packages("cluster",             repos=CRANsite, type="source")
install.packages("gclus",               repos=CRANsite, type="source")
install.packages("coda",                repos=CRANsite, type="source")
install.packages("codetools",           repos=CRANsite, type="source")
install.packages("foreach",             repos=CRANsite, type="source")
install.packages("doMC",                repos=CRANsite, type="source")
install.packages("foreign",             repos=CRANsite, type="source")
install.packages("gam",                 repos=CRANsite, type="source")
install.packages("gamlss.data",         repos=CRANsite, type="source")
install.packages("gamlss.dist",         repos=CRANsite, type="source")
install.packages("hwriter",             repos=CRANsite, type="source")
install.packages("tmvnsim",              repos=CRANsite, type="source")
install.packages("mnormt",              repos=CRANsite, type="source")
install.packages("mvtnorm",             repos=CRANsite, type="source")
Sys.setenv( PKG_CXXFLAGS='-diag-disable 858' )
install.packages("pcaPP",               repos=CRANsite, type="source")
Sys.unsetenv( 'PKG_CXXFLAGS')
install.packages("lava",                repos=CRANsite, type="source")
install.packages("prodlim",             repos=CRANsite, type="source")
install.packages("pscl",                repos=CRANsite, type="source")
install.packages("BatchJobs",           repos=CRANsite, type="source")
install.packages("sandwich",            repos=CRANsite, type="source")
install.packages("sfsmisc",             repos=CRANsite, type="source")
install.packages("spatial",             repos=CRANsite, type="source")
install.packages("VGAM",                repos=CRANsite, type="source")
install.packages("waveslim",            repos=CRANsite, type="source")
install.packages("xtable",              repos=CRANsite, type="source")
install.packages("profileModel",        repos=CRANsite, type="source")
install.packages("brglm",               repos=CRANsite, type="source")
install.packages("deSolve",             repos=CRANsite, type="source")
install.packages("tseriesChaos",        repos=CRANsite, type="source")
install.packages("fastICA",             repos=CRANsite, type="source")
install.packages("R.methodsS3",         repos=CRANsite, type="source")
install.packages("R.oo",                repos=CRANsite, type="source")
install.packages("cgdsr",               repos=CRANsite, type="source")
install.packages("R.utils",             repos=CRANsite, type="source")
install.packages("R.matlab",            repos=CRANsite, type="source")
install.packages("gridExtra",           repos=CRANsite, type="source")
install.packages("gbm",                 repos=CRANsite, type="source")
install.packages("Formula",             repos=CRANsite, type="source")
install.packages("acepack",             repos=CRANsite, type="source")
install.packages("proto",               repos=CRANsite, type="source")
install.packages("chron",               repos=CRANsite, type="source")
install.packages("knitr",               repos=CRANsite, type="source")
install.packages("htmltools",           repos=CRANsite, type="source")
install.packages("htmlwidgets",         repos=CRANsite, type="source")
install.packages("htmlTable",           repos=CRANsite, type="source")
install.packages("viridis",             repos=CRANsite, type="source")
install.packages("Hmisc",               repos=CRANsite, type="source")
install.packages("fastcluster",         repos=CRANsite, type="source")
install.packages("registry",            repos=CRANsite, type="source")
install.packages("bibtex",              repos=CRANsite, type="source")
install.packages("pkgmaker",            repos=CRANsite, type="source")
install.packages("rngtools",            repos=CRANsite, type="source")
install.packages("doParallel",          repos=CRANsite, type="source")
install.packages("gridBase",            repos=CRANsite, type="source")
BiocManager::install(c("BiocGenerics"), update=FALSE)
BiocManager::install(c("Biobase"),      update=FALSE)
install.packages("NMF",                 repos=CRANsite, type="source")
install.packages("irlba",               repos=CRANsite, type="source")
install.packages("igraph",              repos=CRANsite, type="source")
install.packages("GeneNet",             repos=CRANsite, type="source")
install.packages("ape",                 repos=CRANsite, type="source")
install.packages("RJSONIO",             repos=CRANsite, type="source")
install.packages("caTools",             repos=CRANsite, type="source")
install.packages("gplots",              repos=CRANsite, type="source")
install.packages("ROCR",                repos=CRANsite, type="source")
install.packages('later',               repos=CRANsite, type="source")
install.packages('promises',            repos=CRANsite, type="source")
install.packages('httpuv',              repos=CRANsite, type="source")
install.packages("rjson",               repos=CRANsite, type="source")
install.packages("sourcetools",         repos=CRANsite, type="source")
install.packages("shiny",               repos=CRANsite, type="source")
install.packages("seqinr",              repos=CRANsite, type="source")
install.packages("LearnBayes",          repos=CRANsite, type="source")
install.packages("deldir",              repos=CRANsite, type="source")
install.packages("gmodels",             repos=CRANsite, type="source")
install.packages("spData",              repos=CRANsite, type="source")
install.packages("expm",                repos=CRANsite, type="source")
install.packages("spdep",               repos=CRANsite, type="source")
install.packages("vegan",               repos=CRANsite, type="source")
install.packages("adegenet",            repos=CRANsite, type="source")
install.packages("progress",            repos=CRANsite, type="source")
install.packages("rncl",                repos=CRANsite, type="source")
install.packages("rmarkdown",           repos=CRANsite, type="source")
install.packages("reshape",             repos=CRANsite, type="source")
install.packages("xml2",                repos=CRANsite, type="source")
install.packages("triebeard",           repos=CRANsite, type="source")
install.packages("urltools",            repos=CRANsite, type="source")
install.packages("httpcode",            repos=CRANsite, type="source")
install.packages("crul",                repos=CRANsite, type="source")
install.packages("bold",                repos=CRANsite, type="source")
install.packages("rredlist",            repos=CRANsite, type="source")
install.packages("rentrez",             repos=CRANsite, type="source")
install.packages("rotl",                repos=CRANsite, type="source")
install.packages("WikipediR",           repos=CRANsite, type="source")
install.packages("solrium",             repos=CRANsite, type="source")
install.packages("WikidataR",           repos=CRANsite, type="source")
install.packages("ritis",               repos=CRANsite, type="source")
install.packages("worrms",              repos=CRANsite, type="source")
install.packages("natserv",             repos=CRANsite, type="source")
install.packages("wikitaxa",            repos=CRANsite, type="source")
install.packages("phangorn",            repos=CRANsite, type="source")
install.packages("uuid",                repos=CRANsite, type="source")
install.packages("conditionz",          repos=CRANsite, type="source")
install.packages("taxize",              repos=CRANsite, type="source")
install.packages("RNeXML",              repos=CRANsite, type="source")
install.packages("phylobase",           repos=CRANsite, type="source")
install.packages("adephylo",            repos=CRANsite, type="source")
install.packages("magick",              repos=CRANsite, type="source")
install.packages("animation",           repos=CRANsite, type="source")
install.packages("calibrate",           repos=CRANsite, type="source")
install.packages("clusterGeneration",   repos=CRANsite, type="source")
install.packages("raster",              repos=CRANsite, type="source")
install.packages("dismo",               repos=CRANsite, type="source")
install.packages("extrafontdb",         repos=CRANsite, type="source")
install.packages("Rttf2pt1",            repos=CRANsite, type="source")
install.packages("extrafont",           repos=CRANsite, type="source")
install.packages("fields",              repos=CRANsite, type="source")
install.packages("shapefiles",          repos=CRANsite, type="source")
install.packages("fossil",              repos=CRANsite, type="source")
install.packages("geiger",              repos=CRANsite, type="source")
install.packages("glmnet",              repos=CRANsite, type="source")
install.packages("miniUI",              repos=CRANsite, type="source")
install.packages("webshot",             repos=CRANsite, type="source")
install.packages("crosstalk",           repos=CRANsite, type="source")
install.packages("manipulateWidget",    repos=CRANsite, type="source")
install.packages("labdsv",              repos=CRANsite, type="source")
install.packages("stabs",               repos=CRANsite, type="source")
install.packages("modeltools",          repos=CRANsite, type="source")
install.packages("strucchange",         repos=CRANsite, type="source")
install.packages("TH.data",             repos=CRANsite, type="source")
install.packages("multcomp",            repos=CRANsite, type="source")
install.packages("libcoin",             repos=CRANsite, type="source")
install.packages("matrixStats",         repos=CRANsite, type="source")
install.packages("coin",                repos=CRANsite, type="source")
install.packages("party",               repos=CRANsite, type="source")
install.packages("inum",                repos=CRANsite, type="source")
install.packages("partykit",            repos=CRANsite, type="source")
install.packages("mboost",              repos=CRANsite, type="source")
install.packages("msm",                 repos=CRANsite, type="source")
install.packages("nor1mix",             repos=CRANsite, type="source")
install.packages("np",                  repos=CRANsite, type="source")
install.packages("polynom",             repos=CRANsite, type="source")
install.packages("polspline",           repos=CRANsite, type="source")
install.packages("rms",                 repos=CRANsite, type="source")
install.packages("RWekajars",           repos=CRANsite, type="source")
install.packages("RWeka",               repos=CRANsite, type="source")
install.packages("slam",                repos=CRANsite, type="source")
install.packages("tm",                  repos=CRANsite, type="source")
install.packages("TraMineR",            repos=CRANsite, type="source")
install.packages("chemometrics",        repos=CRANsite, type="source")
install.packages("FNN",                 repos=CRANsite, type="source")
install.packages("ipred",               repos=CRANsite, type="source")
install.packages("miscTools",           repos=CRANsite, type="source")
install.packages("maxLik",              repos=CRANsite, type="source")
install.packages("gbRd",                repos=CRANsite, type="source")
install.packages("Rdpack",              repos=CRANsite, type="source")
install.packages("dfidx",               repos=CRANsite, type="source")
install.packages("mlogit",              repos=CRANsite, type="source")
install.packages("getopt",              repos=CRANsite, type="source")
install.packages("gsalib",              repos=CRANsite, type="source")
install.packages("optparse",            repos=CRANsite, type="source")
install.packages("labelled",            repos=CRANsite, type="source")
install.packages("R.cache",             repos=CRANsite, type="source")
install.packages("rematch2",            repos=CRANsite, type="source")
install.packages("styler",              repos=CRANsite, type="source")
install.packages("questionr",           repos=CRANsite, type="source")
install.packages("klaR",                repos=CRANsite, type="source")
install.packages("neuRosim",            repos=CRANsite, type="source")
install.packages("locfit",              repos=CRANsite, type="source")
install.packages("GGally",              repos=CRANsite, type="source")
install.packages("beanplot",            repos=CRANsite, type="source")
install.packages("clValid",             repos=CRANsite, type="source")
install.packages("DiscriMiner",         repos=CRANsite, type="source")
install.packages("ellipse",             repos=CRANsite, type="source")
install.packages("leaps",               repos=CRANsite, type="source")
install.packages("pbkrtest",            repos=CRANsite, type="source")
install.packages("rematch",             repos=CRANsite, type="source")
install.packages("cellranger",          repos=CRANsite, type="source")
install.packages("zip",                 repos=CRANsite, type="source")
install.packages("readxl",              repos=CRANsite, type="source")
install.packages("openxlsx",            repos=CRANsite, type="source")
install.packages("carData",             repos=CRANsite, type="source")
install.packages("maptools",            repos=CRANsite, type="source")
install.packages("rio",                 repos=CRANsite, type="source")
install.packages("car",                 repos=CRANsite, type="source")
install.packages("flashClust",          repos=CRANsite, type="source")
install.packages("ggrepel",          repos=CRANsite, type="source")
install.packages("FactoMineR",          repos=CRANsite, type="source")
install.packages("flexclust",           repos=CRANsite, type="source")
install.packages("flexmix",             repos=CRANsite, type="source")
install.packages("prabclus",            repos=CRANsite, type="source")
install.packages("diptest",             repos=CRANsite, type="source")
install.packages("trimcluster",         repos=CRANsite, type="source")
install.packages("fpc",                 repos=CRANsite, type="source")
install.packages("BiasedUrn",           repos=CRANsite, type="source")
install.packages("TeachingDemos",       repos=CRANsite, type="source")
install.packages("base64",              repos=CRANsite, type="source")
install.packages("doRNG",               repos=CRANsite, type="source")
install.packages("nleqslv",             repos=CRANsite, type="source")
install.packages("Deriv",               repos=CRANsite, type="source")
install.packages("RGCCA",               repos=CRANsite, type="source")
install.packages("pheatmap",            repos=CRANsite, type="source")
install.packages("pvclust",             repos=CRANsite, type="source")
install.packages("RCircos",             repos=CRANsite, type="source")
install.packages("lambda.r",            repos=CRANsite, type="source")
install.packages("futile.options",      repos=CRANsite, type="source")
install.packages("futile.logger",       repos=CRANsite, type="source")
install.packages("VennDiagram",         repos=CRANsite, type="source")
install.packages("xlsxjars",            repos=CRANsite, type="source")
install.packages("xlsx",                repos=CRANsite, type="source")
install.packages("fma",                 repos=CRANsite, type="source") # Cannot be installed as long as tseries does not work.
install.packages("expsmooth",           repos=CRANsite, type="source") # Cannot be installed as long as tseries does not work.
install.packages("fpp",                 repos=CRANsite, type="source") # Cannot be installed as long as tseries does not work.
install.packages("tensor",              repos=CRANsite, type="source")
install.packages("polyclip",            repos=CRANsite, type="source")
install.packages("goftest",             repos=CRANsite, type="source")
install.packages("spatstat.utils",      repos=CRANsite, type="source")
install.packages("spatstat.data",       repos=CRANsite, type="source")
install.packages("spatstat",            repos=CRANsite, type="source")
install.packages("gdalUtils",           repos=CRANsite, type="source") # Needs rgdal which does not compile at the moment.
install.packages("pracma",              repos=CRANsite, type="source")
install.packages("bio3d",               repos=CRANsite, type="source")
install.packages("AUC",                 repos=CRANsite, type="source")
install.packages("interpretR",          repos=CRANsite, type="source")
install.packages("cvAUC",               repos=CRANsite, type="source")
install.packages("SuperLearner",        repos=CRANsite, type="source")
install.packages("mediation",           repos=CRANsite, type="source")
install.packages("lubridate",           repos=CRANsite, type="source")
install.packages("gower",               repos=CRANsite, type="source")
install.packages("recipes",             repos=CRANsite, type="source")
install.packages("caret",               repos=CRANsite, type="source")
install.packages("adabag",              repos=CRANsite, type="source")
install.packages("parallelMap",         repos=CRANsite, type="source")
install.packages("ParamHelpers",        repos=CRANsite, type="source")
install.packages("ggvis",               repos=CRANsite, type="source")
install.packages("mlr",                 repos=CRANsite, type="source")
install.packages("unbalanced",          repos=CRANsite, type="source")
install.packages("RSNNS",               repos=CRANsite, type="source")
install.packages("abc.data",            repos=CRANsite, type="source")
install.packages("abc",                 repos=CRANsite, type="source")
install.packages("lhs",                 repos=CRANsite, type="source")
install.packages("tensorA",             repos=CRANsite, type="source")
install.packages("EasyABC",             repos=CRANsite, type="source")
install.packages("shape",               repos=CRANsite, type="source")
install.packages("whisker",             repos=CRANsite, type="source")
install.packages("commonmark",          repos=CRANsite, type="source")
install.packages("roxygen2",            repos=CRANsite, type="source")
install.packages("git2r",               repos=CRANsite, type="source") # Needs libgit2 which we don't have on our system, so it is not fully functional.
install.packages("rversions",           repos=CRANsite, type="source")
install.packages("ini",                 repos=CRANsite, type="source")
install.packages("clisymbols",          repos=CRANsite, type="source")
install.packages("fs",                  repos=CRANsite, type="source")
install.packages("gh",                  repos=CRANsite, type="source")
install.packages("xopen",               repos=CRANsite, type="source")
install.packages("usethis",             repos=CRANsite, type="source")
install.packages("sessioninfo",         repos=CRANsite, type="source")
install.packages("rcmdcheck",           repos=CRANsite, type="source")
install.packages("remotes",             repos=CRANsite, type="source")
install.packages("rex",                 repos=CRANsite, type="source")
install.packages("covr",                repos=CRANsite, type="source")
install.packages("DT",                  repos=CRANsite, type="source")
install.packages("devtools",            repos=CRANsite, type="source")
install.packages("Rook",                repos=CRANsite, type="source")
install.packages("RMTstat",             repos=CRANsite, type="source")
install.packages("Lmoments",            repos=CRANsite, type="source")
install.packages("distillery",          repos=CRANsite, type="source")
install.packages("extRemes",            repos=CRANsite, type="source")
install.packages("pixmap",              repos=CRANsite, type="source")
install.packages("tkrplot",             repos=CRANsite, type="source")
install.packages("misc3d",              repos=CRANsite, type="source")
install.packages("ks",                  repos=CRANsite, type="source")
install.packages("logcondens",          repos=CRANsite, type="source")
install.packages("Iso",                 repos=CRANsite, type="source")
install.packages("clusterRepro",        repos=CRANsite, type="source")
install.packages("randomForestSRC",     repos=CRANsite, type="source")
install.packages("sm",                  repos=CRANsite, type="source")
install.packages("psych",               repos=CRANsite, type="source")
install.packages("pbivnorm",            repos=CRANsite, type="source")
install.packages("lavaan",              repos=CRANsite, type="source")
install.packages("matrixcalc",          repos=CRANsite, type="source")
install.packages("arm",                 repos=CRANsite, type="source")
install.packages("mi",                  repos=CRANsite, type="source")
install.packages("visNetwork",          repos=CRANsite, type="source")
install.packages("downloader",          repos=CRANsite, type="source")
install.packages("influenceR",          repos=CRANsite, type="source")
install.packages("servr",               repos=CRANsite, type="source")
install.packages("rgexf",               repos=CRANsite, type="source")
install.packages("DiagrammeR",          repos=CRANsite, type="source")
install.packages("sem",                 repos=CRANsite, type="source")
install.packages("statnet.common",      repos=CRANsite, type="source")
install.packages("network",             repos=CRANsite, type="source")
install.packages("sna",                 repos=CRANsite, type="source")
install.packages("huge",                repos=CRANsite, type="source")
install.packages("d3Network",           repos=CRANsite, type="source")
install.packages("BDgraph",             repos=CRANsite, type="source")
install.packages("tweenr",              repos=CRANsite, type="source")
install.packages("qgforce",             repos=CRANsite, type="source")
install.packages("qraphlayouts",        repos=CRANsite, type="source")
install.packages("pbapply",             repos=CRANsite, type="source")
install.packages("tidygraph",           repos=CRANsite, type="source")
install.packages("ggraph",              repos=CRANsite, type="source")
install.packages("qgraph",              repos=CRANsite, type="source")
install.packages("diveRsity",           repos=CRANsite, type="source")
install.packages("doSNOW",              repos=CRANsite, type="source")
install.packages("geepack",             repos=CRANsite, type="source")
install.packages("pim",                 repos=CRANsite, type="source")
#
# UAntwerpen-requested packages
# We rely on R to install all depencies that we may have missed.
#
#
# BioConductor.
# We only install a subset of BioConductor packages.
#

BiocManager::install(c('DynDoc'),              update=FALSE)
BiocManager::install(c('limma'),               update=FALSE)
BiocManager::install(c('edgeR'),               update=FALSE)
BiocManager::install(c('gdsfmt'),              update=FALSE)
BiocManager::install(c('illuminaio'),          update=FALSE)
BiocManager::install(c('preprocessCore'),      update=FALSE)
BiocManager::install(c('RNASeqPower'),         update=FALSE)
BiocManager::install(c('Rsubread'),            update=FALSE)
BiocManager::install(c('qvalue'),              update=FALSE)
BiocManager::install(c('widgetTools'),         update=FALSE)
BiocManager::install(c('zlibbioc'),            update=FALSE)
BiocManager::install(c('impute'),              update=FALSE)
install.packages("shinyFiles",                 repos=CRANsite, type="source")
install.packages("samr",                       repos=CRANsite, type="source")
BiocManager::install(c('tkWidgets'),           update=FALSE)
BiocManager::install(c('Mfuzz'),               update=FALSE)
BiocManager::install(c('pcaMethods'),          update=FALSE)
BiocManager::install(c('S4Vectors'),           update=FALSE)
BiocManager::install(c('IRanges'),             update=FALSE)
BiocManager::install(c('GenomeInfoDbData'),    update=FALSE)
BiocManager::install(c('GenomeInfoDb'),        update=FALSE)
BiocManager::install(c('AnnotationDbi'),       update=FALSE)
BiocManager::install(c('AnnotationForge'),     update=FALSE)
BiocManager::install(c('GO.db'),               update=FALSE)
BiocManager::install(c('org.Hs.eg.db'),        update=FALSE)
BiocManager::install(c('KEGG.db'),             update=FALSE)
BiocManager::install(c('PFAM.db'),             update=FALSE)
BiocManager::install(c('hgu133plus2.db'),      update=FALSE)
BiocManager::install(c('XVector'),             update=FALSE)
BiocManager::install(c('DelayedArray'),        update=FALSE)
BiocManager::install(c('BiocParallel'),        update=FALSE)
BiocManager::install(c('Rhtslib'),             update=FALSE)
BiocManager::install(c('GenomicRanges'),       update=FALSE)
BiocManager::install(c('SummarizedExperiment'), update=FALSE)
install.packages("dbplyr",              repos=CRANsite, type="source")
BiocManager::install(c('Biostrings'),          update=FALSE)
BiocManager::install(c('Rsamtools'),           update=FALSE)
BiocManager::install(c('GenomicAlignments'),   update=FALSE)
install.packages("rappdirs",             repos=CRANsite, type="source")
BiocManager::install(c('BiocFileCache'),       update=FALSE)
BiocManager::install(c('rtracklayer'),         update=FALSE)
BiocManager::install(c('biomaRt'),             update=FALSE)
BiocManager::install(c('GenomicFeatures'),     update=FALSE)
BiocManager::install(c('TxDb.Hsapiens.UCSC.hg19.knownGene'),   update=FALSE)
BiocManager::install(c('ShortRead'),           update=FALSE)
BiocManager::install(c('graph'),               update=FALSE)
BiocManager::install(c('Rgraphviz'),           update=FALSE)
BiocManager::install(c('affyio'),              update=FALSE)
BiocManager::install(c('affy'),                update=FALSE)
BiocManager::install(c('marray'),              update=FALSE)
BiocManager::install(c('CGHbase'),             update=FALSE)
BiocManager::install(c('RBGL'),                update=FALSE)
BiocManager::install(c('annaffy'),             update=FALSE)
BiocManager::install(c('gcrma'),               update=FALSE)
BiocManager::install(c('oligoClasses'),        update=FALSE)
BiocManager::install(c('baySeq'),              update=FALSE)
BiocManager::install(c('DEGseq'),              update=FALSE)
BiocManager::install(c('bumphunter'),          update=FALSE)
BiocManager::install(c('multtest'),            update=FALSE)
install.packages("scrime",                     repos=CRANsite, type="source")
BiocManager::install(c('siggenes'),            update=FALSE)
BiocManager::install(c('genoset'),             update=FALSE)
BiocManager::install(c('NOISeq'),              update=FALSE)
BiocManager::install(c('annotate'),            update=FALSE)
BiocManager::install(c('GSEABase'),            update=FALSE)
BiocManager::install(c('genefilter'),          update=FALSE)
BiocManager::install(c('Category'),            update=FALSE)
#HERE
BiocManager::install(c('GOstats'),             update=FALSE)
BiocManager::install(c('BSgenome'),            update=FALSE)
BiocManager::install(c('VariantAnnotation'),   update=FALSE)
BiocManager::install(c('interactiveDisplayBase'), update=FALSE)
BiocManager::install(c('AnnotationHub'),       update=FALSE)
BiocManager::install(c('AnnotationFilter'),    update=FALSE)
BiocManager::install(c('ProtGenerics'),        update=FALSE)
BiocManager::install(c('ensembldb'),           update=FALSE)
BiocManager::install(c('biovizBase'),          update=FALSE)
BiocManager::install(c('OrganismDbi'),         update=FALSE)
BiocManager::install(c('ggbio'),               update=FALSE)
BiocManager::install(c('geneplotter'),         update=FALSE)
BiocManager::install(c('DESeq2'),              update=FALSE)
BiocManager::install(c('ReportingTools'),      update=FALSE)
BiocManager::install(c('Glimma'),              update=FALSE)
BiocManager::install(c('affycoretools'),       update=FALSE)
BiocManager::install(c('Homo.sapiens'),        update=FALSE)
BiocManager::install(c('BSgenome.Hsapiens.UCSC.hg19'), update=FALSE)
BiocManager::install(c('AgiMicroRna'),         update=FALSE)
#HERE
BiocManager::install(c('geneLenDataBase'),     update=FALSE)
BiocManager::install(c('goseq'),               update=FALSE)
BiocManager::install(c('KEGGREST'),            update=FALSE)
BiocManager::install(c('KEGGgraph'),           update=FALSE)
BiocManager::install(c('KEGGprofile'),         update=FALSE)
BiocManager::install(c('GEOquery'),            update=FALSE)
BiocManager::install(c('Rhdf5lib'),            update=FALSE)
BiocManager::install(c('rhdf5'),               update=FALSE)
BiocManager::install(c('HDF5Array'),           update=FALSE)
BiocManager::install(c('DelayedMatrixStats'),  update=FALSE)
BiocManager::install(c('minfi'),               update=FALSE)
BiocManager::install(c('FDb.InfiniumMethylation.hg19'), update=FALSE)
BiocManager::install(c('methylumi'),           update=FALSE)
BiocManager::install(c('lumi'),                update=FALSE)
install.packages("admisc",                     repos=CRANsite, type="source")
install.packages("venn",                       repos=CRANsite, type="source")
BiocManager::install(c('maSigPro'),            update=FALSE)
BiocManager::install(c('SPIA'),                update=FALSE)
BiocManager::install(c('Gviz'),                update=FALSE)
BiocManager::install(c('cummeRbund'),          update=FALSE)
BiocManager::install(c('GenomicFiles'),        update=FALSE)
BiocManager::install(c('derfinderHelper'),     update=FALSE)
BiocManager::install(c('derfinder'),           update=FALSE)
BiocManager::install(c('polyester'),           update=FALSE)
BiocManager::install(c('sigaR'),               update=FALSE)
BiocManager::install(c('Wrench'),              update=FALSE)
BiocManager::install(c('metagenomeSeq'),       update=FALSE)
#
# Other requeste packages
#
# Mzmatch, depends on BioConductor, but no longer present since R 3.4
install.packages("ptw",                        repos=CRANsite)
install.packages("tcltk2",                     repos=CRANsite)
install.packages("MALDIquant",                 repos=CRANsite, type="source")
install.packages("ncdf4",                      repos=CRANsite)
Sys.setenv( PKG_CXXFLAGS='-diag-disable 858' )
BiocManager::install(c('mzR'),                 update=FALSE)
Sys.unsetenv( 'PKG_CXXFLAGS')
BiocManager::install(c('vsn'),                 update=FALSE)
BiocManager::install(c('mzID'),                update=FALSE)
BiocManager::install(c('MSnbase'),             update=FALSE)
BiocManager::install(c('MassSpecWavelet'),     update=FALSE)
BiocManager::install(c('xcms'),                update=FALSE)
# Problem: mzmatch not available for R 3.4.3...
#install.packages("mzmatch.R",                  repos="http://R-Forge.R-project.org") 
#
# dclone and dependencies
install.packages("R2WinBUGS",                  repos=CRANsite)
install.packages("rjags",                      repos=CRANsite)
install.packages("R2jags",                     repos=CRANsite)
install.packages("RcppParallel,                repos=CRANsite)
install.packages("inline",                     repos=CRANsite)
install.packages("loo",                        repos=CRANsite)
install.packages("StanHeaders",                repos=CRANsite)
install.packages("rstan"                       repos=CRANsite)
install.packages("dclone",                     repos=CRANsite)
#
# future 
install.packages("listenv",                    repos=CRANsite)
install.packages("globals",                    repos=CRANsite)
install.packages("future",                     repos=CRANsite)
#
# CSFA, and its dependencies
BiocManager::install(c('fabia'),               update=FALSE)
install.packages("V8",                         repos=CRANsite)
install.packages("elasticnet",                 repos=CRANsite)
install.packages("snowFT",                     repos=CRANsite)
install.packages("randomcoloR",                repos=CRANsite)
install.packages("CSFA",                       repos=CRANsite)
#
# dada2 (dependencies already installed)
BiocManager::install(c('dada2'),               update=FALSE)
#
# phyloseq and dependencies
BiocManager::install(c('biomformat'),          update=FALSE)
BiocManager::install(c('phyloseq'),            update=FALSE)
#
# DECIPHER
BiocManager::install(c('DECIPHER'),            update=FALSE)



